
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 623910
	#The name of the modpack
	modpackName = "Fantasy Realm"
	#The version of the modpack
	modpackVersion = "v8"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

